version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mnist
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mnistdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mnist"]
      interval: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://mnist:secret@db:5432/mnistdb"
    ports:
      - "7860:7860"
    volumes:
      - ./model:/app/model

volumes:
  db_data:
